Shellcheck fixes for buildrpm.
As usual, this is mostly for cleanup and maintainability.

diff --git a/xCAT-genesis-builder/buildrpm b/xCAT-genesis-builder/buildrpm
--- a/xCAT-genesis-builder/buildrpm
+++ b/xCAT-genesis-builder/buildrpm
@@ -1,3 +1,5 @@
+#!/bin/bash
+#
 # Build the xCAT-genesis-base rpm on a host system.
 # Option 1:  install the xCAT-genesis-builder rpm (that includes this file) on a system installed with
 #            the distro you want to use to build xCAT-genesis-base.
@@ -8,10 +10,10 @@
 # Currently, *Fedora 28* and *RedHat 8* are the only OSes supported to build genesis-base for ppc64, and Centos 6.5 for x86_64
 
 HOSTOS="$1"
-DIR=`dirname $0`
-#DIR=`realpath $DIR`
-DIR=`readlink -f $DIR`
-BUILDARCH=`uname -m`
+DIR=$(dirname "$0")
+#DIR=`realpath $DIR)
+DIR=$(readlink -f "$DIR")
+BUILDARCH=$(uname -m)
 REQUIRED_PACKAGES="vconfig rsyslog rpmdevtools rpm-build screen lldpad mstflint ipmitool pciutils mdadm dosfstools usbutils bind-utils psmisc nmap-ncat ethtool kexec-tools"
 
 if grep 'REPLACE_CURRENT_VERSION' xCAT-genesis-base.spec &>/dev/null; then
@@ -20,13 +22,13 @@ if grep 'REPLACE_CURRENT_VERSION' xCAT-genesis-base.spec &>/dev/null; then
 fi
 
 #For Openpower
-if [ -z $1 ]; then
-    if [ $BUILDARCH = "ppc64le" ]; then
+if [ -z "$1" ]; then
+    if [ "$BUILDARCH" = "ppc64le" ]; then
         HOSTOS="Pegas1.0"
         BUILDARCH="ppc64"
-    elif [ $BUILDARCH = "ppc64" ]; then
+    elif [ "$BUILDARCH" = "ppc64" ]; then
         HOSTOS="fedora26"
-    elif [ $BUILDARCH = "x86_64" ]; then
+    elif [ "$BUILDARCH" = "x86_64" ]; then
         REQUIRED_PACKAGES="$REQUIRED_PACKAGES efibootmgr bc"
         HOSTOS="centos7"
     fi
@@ -35,15 +37,14 @@ fi
 pkglist=$(rpm -qa)
 to_install=""
 for required_package in $REQUIRED_PACKAGES; do
-    if ! echo $pkglist |grep $required_package &>/dev/null; then
+    if ! echo "$pkglist" |grep "$required_package" &>/dev/null; then
         to_install="$to_install $required_package"
     else
         echo "$required_package already installed"
     fi
 done
 if [ -n "$to_install" ]; then
-    yum install -y $to_install
-    if [ $? -ne 0 ]; then
+    if ! yum install -y "$to_install"; then
         echo "ERROR: Can not install required required packages, make sure EPEL repository is configured"
         exit 1
     fi
@@ -62,48 +63,55 @@ else
 fi
 
 DRACUTMODS="96chrony 97xcat"
-cd $DIR
+cd "$DIR" || exit 1
 mkdir -p $DRACUTMODDIR/
 for mod in $DRACUTMODS; do
-    cp -a $mod $DRACUTMODDIR
+    cp -a "$mod" "$DRACUTMODDIR"
 done
 
 mkdir -p /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs
 
 # run dracut
 if [ "$HOSTOS" = "mcp" ]; then
-	KPATH=`/bin/ls -d /lib/modules/*`
-	KERNELVERSION=`basename $KPATH`
-	echo Creating the initramfs in /tmp/xcatgenesis.$$.rfs using dracut and kernel $KERNELVERSION ...
+    KPATH=$(/bin/ls -d /lib/modules/*)
+    KERNELVERSION=$(basename "$KPATH")
+    echo "Creating the initramfs in /tmp/xcatgenesis.$$.rfs using dracut and kernel $KERNELVERSION ..."
 else
-	echo Creating the initramfs in /tmp/xcatgenesis.$$.rfs using dracut ...
+    echo Creating the initramfs in /tmp/xcatgenesis.$$.rfs using dracut ...
 fi
 # On Fedora 20 ppc64, dracut uses host-only mode by default
 if [ $BUILDARCH = "ppc64" ]; then
-    dracut -m "xcat" -N -f /tmp/xcatgenesis.$$.rfs $KERNELVERSION
+    dracut -m "xcat" -N -f /tmp/xcatgenesis.$$.rfs "$KERNELVERSION"
 else
-    dracut -m "xcat" --no-early-microcode -N -f /tmp/xcatgenesis.$$.rfs $KERNELVERSION
+    dracut -m "xcat" --no-early-microcode -N -f /tmp/xcatgenesis.$$.rfs "$KERNELVERSION"
 fi
 
+# shellcheck disable=SC2181
 if [ $? -ne 0 ]; then
     echo "ERROR - creating the initramfs, please correct the issues and try again"
     exit 1
 fi
 
-echo Expanding the initramfs into /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs ...
-cd /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs
+echo "Expanding the initramfs into /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs ..."
+cd /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs || exit 1
 
 zcat /tmp/xcatgenesis.$$.rfs|cpio -dumi
 
 # add the perl library
 # add /usr/share/ntp/lib for Fedora26 ppc64, the ntp-perl will installed libraries under it
-PERL_LIB_DIR="/usr/share/perl5 /usr/lib64/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/share/ntp/lib"
-for d in `echo $PERL_LIB_DIR`; do
-    if [ -e $d ]; then
+PERL_LIB_DIR=(
+/usr/share/perl5
+/usr/lib64/perl5
+/usr/local/lib64/perl5
+/usr/local/share/perl5
+/usr/share/ntp/lib
+)
+for d in "${PERL_LIB_DIR[@]}"; do
+    if [ -e "$d" ]; then
         echo Adding perl libary "$d"
         TEMP_DIR=/tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs/"$d"
-        mkdir -p $TEMP_DIR
-        cp -a -t $TEMP_DIR $d/.
+        mkdir -p "$TEMP_DIR"
+        cp -a -t "$TEMP_DIR" "$d"/.
     fi
 done
 
@@ -112,22 +120,22 @@ mkdir -p /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs/e
 
 # add the kernel
 if [ "$HOSTOS" = "mcp" ]; then
-	echo Adding kernel /boot/vmlinuz-* ...
-	cp /boot/vmlinuz-* /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/kernel
+    echo Adding kernel /boot/vmlinuz-* ...
+    cp /boot/vmlinuz-* /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/kernel
 else
-	echo Adding kernel /boot/vmlinuz-$BUILDARCH ...
-	cp /boot/vmlinuz-`uname -r` /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/kernel
+    echo Adding kernel /boot/vmlinuz-$BUILDARCH ...
+    cp /boot/vmlinuz-"$(uname -r)" /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/kernel
 fi
-cd -
+cd - || exit 1
 
 # create tar file
 echo Tarring /tmp/xcatgenesis.$$/opt into ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 ...
-cd /tmp/xcatgenesis.$$
+cd /tmp/xcatgenesis.$$ || exit 1
 tar jcf ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 opt
 
 # build the rpm
-echo Building xCAT-genesis-base rpm from ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 and $DIR/xCAT-genesis-base.spec ...
-rpmbuild -ba $DIR/xCAT-genesis-base.spec
+echo "Building xCAT-genesis-base rpm from ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 and $DIR/xCAT-genesis-base.spec ..."
+rpmbuild -ba "$DIR"/xCAT-genesis-base.spec
 for mod in $DRACUTMODS; do
-    rm -rf $DRACUTMODDIR/$mod
+    rm -rf "${DRACUTMODDIR:?}"/"$mod"
 done
